### ISSUE TITLE
AttributeError: 'Stripe' object has no attribute 'stripe_publishable_key'

### ISSUE THREAD

**Issue by aiscience01** [Sumukh/Ignite#404]
Hello

Downloaded and tried to run the code. Followed the instructions to set the environment, and set variables including strip keys in .env.local. Tested that these values are read and set in the application by printing stripe.stripe_publishable_key in appname/services/strip.py (in function init_app).  The app comes up fine. In the web app, when clicking on Billing (path: settings/billing), the application raises the following error:

Traceback (most recent call last):
  File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/admin/ignite-master/appname/controllers/settings.py", line 67, in billing
    stripe_publishable_key=stripe.stripe_publishable_key)
AttributeError: 'Stripe' object has no attribute 'stripe_publishable_key'

Can you please help what causes this?

**Comment by aiscience01** [comment]
It seems the variable that is initialized in stripe.y is 'stripe.publishable_key' and not 'stripe.stripe_publishable_key'. Code need to be changed to fix this.
