### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'form' is undefined

### ISSUE THREAD

**Issue by aiscience01** [Sumukh/Ignite#405]
Hello,

After doing a successful subscription with Stripe, the page has to be redirected to the team page, apparently. However, the following error is raised on the settings/billing page.  Appreciate the help.

jinja2.exceptions.UndefinedError
jinja2.exceptions.UndefinedError: 'form' is undefined

Traceback (most recent call last)
File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
return original_handler(e)
File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
return original_handler(e)
File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
return view_func(**req.view_args)
File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/home/admin/ignite-master/appname/controllers/settings.py", line 66, in billing
return render_template('/settings/billing.html', plans=plans_by_name,
File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
return _render(
File "/home/admin/ignite-master/env/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
rv = template.render(context)
File "/home/admin/ignite-master/env/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
self.environment.handle_exception()
File "/home/admin/ignite-master/env/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
raise rewrite_traceback_stack(source=source)
File "/home/admin/ignite-master/appname/templates/settings/billing.html", line 2, in top-level template code
{% from "helpers/_formhelpers.html" import render_field %}
File "/home/admin/ignite-master/appname/templates/tabler/dashboard_base.html", line 45, in top-level template code
{% block body %}
File "/home/admin/ignite-master/appname/templates/settings/billing.html", line 76, in block 'body'
{{ form.hidden_tag() }}
File "/home/admin/ignite-master/env/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined

**Comment by Sumukh** [comment]
Thanks for the report. This is fixed in #405
